import requests
from bs4 import BeautifulSoup
import lxml
import time
import datetime
from datetime import timezone
import pytz
from pythorhead import Lemmy
import os # for env file
from dotenv import load_dotenv
from Database import Database

load_dotenv()

db = Database()

current_time = int(time.time() * 1000) # in milliseconds since 01/01/1970

# time_unil = how long before kick off to post a new thread with channels. (in milliseconds)
time_until = 43200000 # 12 hours
#time_until = 86400000 # 24 hours
#time_until = 864000000 # 10 days 

base_url = "https://www.livesoccertv.com"
team_url = base_url + "/teams/england/arsenal/"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "Referer": "https://www.livesoccertv.com/schedules/"
    }
response = requests.get(team_url, headers=headers)


def get_match_ref():
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, "lxml")
        elements = soup.find("table", {"class": "schedules"})
        table_rows = elements.find_all("tr", {"class": "matchrow"})
        for tr in table_rows:
            table_data = tr.find_all("td")
            match_ref = table_data[4].find("a")["href"]
            match_title = table_data[4].find("a").text
            match_time = int(table_data[2].find("span", {"class": "ts"})["dv"])
            time_until_match = match_time - current_time
            if time_until_match < time_until and time_until_match > 0: # if there is less than 24 hours until the match and the match isnt in the past
                global current_match_time, current_match_title
                current_match_title = match_title
                current_match_time = match_time
                return [match_ref, match_title]
        return False
    elif response.status_code == 429:
        print("Rate Limited. Sleeping...")
        time.sleep(60)

            
    else:
        print("Error getting match ref. Code: " + response.status_code)
        
        



def run():
    if (get_match_ref() is False):
        print("no match ref, quitting")
        quit()
    else:
        ref, match_title = get_match_ref()
    channels = {}
        
    match_page = requests.get(base_url + ref, headers=headers)
    if match_page.status_code == 200:
        
        match_soup = BeautifulSoup(match_page.content, "lxml")
        match_tab_cont = match_soup.find_all("div", {"class": "tab_container"})[1]
        match_sched_cont = match_tab_cont.find("div", {"id": "_schedules"})
        match_channel_cont = match_sched_cont.find("table", {"id": "wc_channels"})
        match_channel_rows = match_channel_cont.find_all("tr")[:-1]
        for row in match_channel_rows:
            #print(row.prettify())
            country_text = row.find("span").text
            channel_name = row.find("a").text
            if channel_name in channels:
                channels[channel_name].append(country_text)
            else:
                channels[channel_name] = [country_text]
        post_to_lemmy(*post_template(match_title, channels))
        
    else:
        print("Error accessing match page. Code: " + str(match_page.status_code))
        
def get_time(zone):
    if zone == "date":
        
        return datetime.datetime.fromtimestamp(current_match_time // 1000).strftime("%A %d %B %Y")
    else:
        tz = pytz.timezone(zone)
        return datetime.datetime.fromtimestamp(current_match_time // 1000).astimezone(tz).strftime("%H:%M")

def post_template(title, channels):


    txt = f"## Kick Off Time \n\n * UK: *{get_time('Europe/London')}* \n * EST: *{get_time('EST')}* \n * PT: *{get_time('US/Pacific')}* \n\n ***"
    for chnl, countries in channels.items():
        txt += "\n### " + chnl + "\n"
        for country in countries:
            txt += "- " + country + "\n"
    txt += "\n\n*This was autogenerated by a bot.*"

    return [title, txt]
        


def post_to_lemmy(title, body):
    #print(os.environ)
    already_posted = db.check_existing(current_match_time)
    if (not already_posted):
        lemmy = Lemmy(os.getenv("INSTANCE"))
        lemmy.log_in(os.getenv("USER"), os.getenv("PASS"))
        community_id = lemmy.discover_community(os.getenv("COMMUNITY"))
        #print(os.getenv("INSTANCE"), os.getenv("USER"), os.getenv("PASS"), os.getenv("COMMUNITY"))
        post = lemmy.post.create(
            community_id, 
            f"[Where to watch] {title} - {get_time('date')}",
            body=body
            )
        if post:
            db.insert_match(current_match_time, current_match_title)
            print("Successfully posted for " + title)
        else:
            print("Could not post for " + title)
    elif (already_posted):
        print("Already posted for this match: " + current_match_title)
        
    #print(title, body)


run()


